### ISSUE TITLE
Addition App GCI

### ISSUE THREAD

**Issue by SachinRammoorthy** [jboss-outreach/anonymous#1]
Hi. I finished creating the addition app for the Google Code In.
PFA

Thanks
(Sachin Rammoorthy)
[Addition.zip](https://github.com/jboss-outreach/anonymous/files/1511021/Addition.zip)

**Comment by garg-anuj** [comment]
@SachinRammoorthy Please add screenshots here

**Comment by SachinRammoorthy** [comment]
Oops sorry adding screenshots now.
![screen shot 2017-11-28 at 11 28 52 pm](https://user-images.githubusercontent.com/20569603/33335765-faec6f8e-d493-11e7-8685-3bad91cb636e.png)

**Comment by opticod** [comment]
Where is `Result number` ? @SachinRammoorthy

**Comment by garg-anuj** [comment]
@SachinRammoorthy Please add result of addition too

**Comment by SachinRammoorthy** [comment]
Addition screenshot attached.

![screen shot 2017-11-28 at 11 33 21 pm](https://user-images.githubusercontent.com/20569603/33335973-a21d9832-d494-11e7-8ecf-87d3de72e06a.png)
![screen shot 2017-11-28 at 11 33 44 pm](https://user-images.githubusercontent.com/20569603/33335985-a75db4b2-d494-11e7-8d57-20048b67d479.png)

**Comment by opticod** [comment]
LGTM! Good Work @SachinRammoorthy

**Comment by SachinRammoorthy** [comment]
Thanks!

**Comment by SachinRammoorthy** [comment]
Hey. Sorry to bother, but can the task be approved on the Google Code-In page?

Thanks a bunch.

**Comment by geek-gupta** [comment]
Yes @SachinRammoorthy
