### ISSUE TITLE
Install Android Studio 3.0 and Hello World app

### ISSUE THREAD

**Issue by Xalion67** [jboss-outreach/anonymous#14]
<img width="1280" alt="app" src="https://user-images.githubusercontent.com/20219933/33345801-a3d646ce-d49e-11e7-9df7-98ff9102c95c.png">

[app.zip](https://github.com/jboss-outreach/anonymous/files/1511719/app.zip)

**Comment by garg-anuj** [comment]
thanks @Xalion67
