### ISSUE TITLE
Installing Android Studio 3.0

### ISSUE THREAD

**Issue by SachinRammoorthy** [jboss-outreach/anonymous#2]
Hi. Screenshots of Android Studio 3.0 installed on my computer attached
![screen shot 2017-11-28 at 11 55 30 pm](https://user-images.githubusercontent.com/20569603/33337072-d4c2b9c2-d497-11e7-930a-8962d61d06bd.png)
![screen shot 2017-11-28 at 11 55 43 pm](https://user-images.githubusercontent.com/20569603/33337078-d8d5aec0-d497-11e7-9120-b90f1323fd11.png)
![screen shot 2017-11-28 at 11 56 39 pm](https://user-images.githubusercontent.com/20569603/33337087-dd9c9a04-d497-11e7-8e4d-0ce056bc81fb.png)

.

**Comment by geek-gupta** [comment]
Good work @SachinRammoorthy
