### ISSUE TITLE
Download and Install Android Studio v3.0.1 and create a "Hello-World " app

### ISSUE THREAD

**Issue by Aakash0005** [jboss-outreach/anonymous#20]
Here is the apk file:
[app-debug.zip](https://github.com/jboss-outreach/anonymous/files/1511977/app-debug.zip)

And here are some Screenshots related to my work.
![screenshot 229](https://user-images.githubusercontent.com/34071419/33349855-ee99bf4c-d4c1-11e7-8447-2ca85fd914fd.png)
![screenshot 228](https://user-images.githubusercontent.com/34071419/33349856-eed8b3dc-d4c1-11e7-9e22-e10cbb7b10c7.png)

**Comment by garg-anuj** [comment]
thanks @Aakash0005
