### ISSUE TITLE
Add two numbers app -Kacper Smal

### ISSUE THREAD

**Issue by kacperospl** [jboss-outreach/anonymous#21]
![addtwonumberscode](https://user-images.githubusercontent.com/24917093/33350570-c261d738-d49f-11e7-8d9d-64520cfee740.PNG)
![addtwonumbersapp](https://user-images.githubusercontent.com/24917093/33350571-c28cf9c2-d49f-11e7-987d-5d0e107759de.PNG)

[AddTwoNumbers-Kacper Smal.zip](https://github.com/jboss-outreach/anonymous/files/1512022/AddTwoNumbers-Kacper.Smal.zip)

**Comment by garg-anuj** [comment]
@kacperospl 🎉
