### ISSUE TITLE
an android app that adds two numbers

### ISSUE THREAD

**Issue by HITGIF** [jboss-outreach/anonymous#22]
APK HERE:
[ADDER.apk.zip](https://github.com/jboss-outreach/anonymous/files/1512094/ADDER.apk.zip)

SCREENSHOTS HERE:
![image](https://user-images.githubusercontent.com/16971971/33351625-9f36f87a-d4df-11e7-87b4-048784eba437.png)
![image](https://user-images.githubusercontent.com/16971971/33351629-ab45e900-d4df-11e7-9bbb-e31ffc3f1819.png)
![image](https://user-images.githubusercontent.com/16971971/33351634-b57c0698-d4df-11e7-9dac-e269a8325091.png)
![image](https://user-images.githubusercontent.com/16971971/33351642-be82e662-d4df-11e7-8fb0-6cfd4881aa4d.png)

**Comment by garg-anuj** [comment]
thanks @HITGIF
