### ISSUE TITLE
Task Submission - Install Android Studio 3.0

### ISSUE THREAD

**Issue by zwliew** [jboss-outreach/anonymous#24]
<img width="960" alt="untitled" src="https://user-images.githubusercontent.com/4538946/33353984-8e782106-d4eb-11e7-94ae-3e1e66917365.png">

![media-20171129](https://user-images.githubusercontent.com/4538946/33354125-37443464-d4ec-11e7-93b3-2703159ed499.png)

**Comment by garg-anuj** [comment]
thanks

**Comment by zwliew** [comment]
Thanks!
