### ISSUE TITLE
an iOS app that adds two numbers

### ISSUE THREAD

**Issue by HITGIF** [jboss-outreach/anonymous#25]
SCREENSHOT OF THE APP
![image](https://user-images.githubusercontent.com/16971971/33356023-2436fa88-d4f5-11e7-9fd1-d24415bf9855.png)

SCREENSHOT OF THE CODE
![image](https://user-images.githubusercontent.com/16971971/33356058-50e5aaca-d4f5-11e7-8324-6150c56fb3f2.png)

**Comment by geek-gupta** [comment]
@HITGIF good work
