### ISSUE TITLE
Submission: Install Android Studio 3.0 ( JBoss Community )

### ISSUE THREAD

**Issue by jennydaman** [jboss-outreach/anonymous#26]
Jennings Zhang

![screenshot_20171128-220846](https://user-images.githubusercontent.com/20404439/33356143-e0b21494-d488-11e7-8af2-64718298af4f.png)

![screenshot from 2017-11-28 22-06-16](https://user-images.githubusercontent.com/20404439/33356150-e76ec17e-d488-11e7-832e-19fcbd37daca.png)

**Comment by garg-anuj** [comment]
thanks
