### ISSUE TITLE
Submission (GCI)- Android Studio 3.0 || Hello World Android App 

### ISSUE THREAD

**Issue by alisyed556** [jboss-outreach/anonymous#31]
<b>APK -</b>

[HelloWorld.apk.zip](https://github.com/jboss-outreach/anonymous/files/1512568/app-debug.apk.zip)
------------------------------------------------------
------------------------------------------------------
<b># Hello World Android App Submission by Syed !</b>

<img width="1280" alt="screen shot 2017-11-29 at 9 58 49 am" src="https://user-images.githubusercontent.com/15706347/33358015-efbcca3e-d4eb-11e7-8141-fa048badba03.png">
<img width="1280" alt="screen shot 2017-11-29 at 9 58 46 am" src="https://user-images.githubusercontent.com/15706347/33358018-f1ed59d6-d4eb-11e7-9792-488bf8f3bc32.png">
<img width="1280" alt="screen shot 2017-11-29 at 9 58 32 am" src="https://user-images.githubusercontent.com/15706347/33358022-fe57ffbe-d4eb-11e7-9355-1013f153b7f2.png">

<br/>
<br/>
----------------------------------------- <big><b>THE APP</big></b> -----------------------------------------

<br/>
<br/>
<img width="349" alt="screen shot 2017-11-29 at 10 29 47 am" src="https://user-images.githubusercontent.com/15706347/33358726-5c0f29c6-d4f0-11e7-8863-dd3cea23748e.png">

**Comment by geek-gupta** [comment]
@alisyed556 good work
