### ISSUE TITLE
Install Android Studio 3.0

### ISSUE THREAD

**Issue by bhoangluu** [jboss-outreach/anonymous#34]
![screenshot from 2017-11-29 00-32-21](https://user-images.githubusercontent.com/22111917/33365491-47ac3cec-d49d-11e7-8499-5bbeec021866.png)

**Comment by bhoangluu** [comment]
![screenshot from 2017-11-29 00-33-38](https://user-images.githubusercontent.com/22111917/33365514-58315624-d49d-11e7-98d7-a71b49cc9553.png)

**Comment by bhoangluu** [comment]
[hellloworldGCI.zip](https://github.com/jboss-outreach/anonymous/files/1515111/hellloworldGCI.zip)

**Comment by opticod** [comment]
Good Work :D !
