### ISSUE TITLE
Write an iOS app to add two numbers.

### ISSUE THREAD

**Issue by g30r93g** [jboss-outreach/anonymous#35]
Here is my Addition app:
[Add Numbers App.zip](https://github.com/jboss-outreach/anonymous/files/1513062/Add.Numbers.App.zip)

**Comment by g30r93g** [comment]
And screenshots:
![screen shot 2017-11-28 at 22 01 48](https://user-images.githubusercontent.com/31825917/33366306-c3c34baa-d4e2-11e7-9fa0-ddcc0e9ad507.jpg)
![screen shot 2017-11-28 at 22 01 57](https://user-images.githubusercontent.com/31825917/33366308-c3e144b6-d4e2-11e7-84f4-ea7382d97e46.jpg)
![screen shot 2017-11-28 at 22 02 06](https://user-images.githubusercontent.com/31825917/33366309-c3ffd7c8-d4e2-11e7-8134-0f1e3663d94f.jpg)
![screen shot 2017-11-28 at 22 02 12](https://user-images.githubusercontent.com/31825917/33366311-c4202424-d4e2-11e7-87ab-cfc0b4b4b09e.jpg)
![screen shot 2017-11-28 at 22 02 18](https://user-images.githubusercontent.com/31825917/33366312-c439b9de-d4e2-11e7-9dcd-d895085287d1.jpg)
![screen shot 2017-11-28 at 22 02 35](https://user-images.githubusercontent.com/31825917/33366313-c4521588-d4e2-11e7-848d-1ccc2d92387c.jpg)
![screen shot 2017-11-29 at 08 54 59](https://user-images.githubusercontent.com/31825917/33366384-08e4b872-d4e3-11e7-9292-28932d7ea49c.jpg)
![screen shot 2017-11-29 at 08 54 44](https://user-images.githubusercontent.com/31825917/33366385-09021688-d4e3-11e7-84de-c7f497f8459a.jpg)

**Comment by geek-gupta** [comment]
@g30r93g good work
