### ISSUE TITLE
Android Studio 3.0

### ISSUE THREAD

**Issue by Adrian2901** [jboss-outreach/anonymous#44]
Done

![](https://i.gyazo.com/f811f89981bc95577a2850cfa4902c99.png)

![](https://i.gyazo.com/dd143f1fb362e2d41b9db79c1dafb1a9.png)

![](https://i.gyazo.com/0010fb3a656c26bc385ee3ae886e6b69.png)

**Comment by opticod** [comment]
Good Work :D !
