### ISSUE TITLE
Hey, This is my first app! I have corrected an rechecked my mistakes, hope you like it! ^_^

### ISSUE THREAD

**Issue by maskdvigilante** [jboss-outreach/anonymous#45]
![gci 1](https://user-images.githubusercontent.com/34087484/33395858-d3351552-d56c-11e7-8b24-22af1d146214.PNG)

![gci 2](https://user-images.githubusercontent.com/34087484/33396143-ac6cdeea-d56d-11e7-9b50-0dd7ee41c601.PNG)
![gci 3](https://user-images.githubusercontent.com/34087484/33396146-ae5d1738-d56d-11e7-9ac1-f08240754d6c.PNG)

[app-debug.apk.zip](https://github.com/jboss-outreach/anonymous/files/1515336/app-debug.apk.zip)

**Comment by opticod** [comment]
Good Work :D !
