### ISSUE TITLE
Addition app

### ISSUE THREAD

**Issue by navanavi3** [jboss-outreach/anonymous#6]
I completed the Addition app. Here's the screenshots and the apk. 😊
[addition app.zip](https://github.com/jboss-outreach/anonymous/files/1511317/addition.app.zip)
![java code](https://user-images.githubusercontent.com/16420415/33339107-161c8780-d49e-11e7-964d-cf58ad36523b.JPG)
![xml preview](https://user-images.githubusercontent.com/16420415/33339109-169a5160-d49e-11e7-9aff-1fece35053b7.JPG)
![screenshot_20171129-004347](https://user-images.githubusercontent.com/16420415/33339215-7cdc651c-d49e-11e7-8949-c0bd8cb48f11.png)

**Comment by geek-gupta** [comment]
good work @navanavi3
