### ISSUE TITLE
First task - Simple App

### ISSUE THREAD

**Issue by G4m3r3k** [jboss-outreach/anonymous#76]
![gci](https://user-images.githubusercontent.com/20950076/33518360-09343498-d794-11e7-8206-878df7f172ec.png)
![screenshot_1512237495](https://user-images.githubusercontent.com/20950076/33518361-094e3cb2-d794-11e7-8e64-435b1035b112.png)

**Comment by yashovardhanagrawal** [comment]
LGTM

Approved

cc @garg-anuj
