### ISSUE TITLE
GCI task-To make a hello-world app

### ISSUE THREAD

**Issue by ritz-238** [jboss-outreach/anonymous#80]
![screen shot 2017-12-02 at 1 40 53 pm](https://user-images.githubusercontent.com/31249504/33525832-10328d02-d85d-11e7-804b-168a3131ac99.png)

This is the code and app is:

![screen shot 2017-12-02 at 1 41 03 pm](https://user-images.githubusercontent.com/31249504/33525855-4bbe26ba-d85d-11e7-8262-cc4289c511c0.png)

**Comment by opticod** [comment]
Good Work @ritz-238  :tada: !
