### ISSUE TITLE
Install Android Studio 3.0 ( JBoss Community )

### ISSUE THREAD

**Issue by camalCasing** [jboss-outreach/anonymous#90]
Here is a screen shot of my hello world app.
![screenshot_2017-12-05-18-55-54](https://user-images.githubusercontent.com/34289009/33639079-4b57e0d8-d9ef-11e7-8e46-f72b38505e07.png)
Here is the code for the hello world app.
![screenshot 1](https://user-images.githubusercontent.com/34289009/33639090-551f74fa-d9ef-11e7-83a1-dfae98a3f93d.png)
![screenshot 2](https://user-images.githubusercontent.com/34289009/33639093-57944f8a-d9ef-11e7-9c8e-f2578b460a52.png)

**Comment by garg-anuj** [comment]
Good work
