### ISSUE TITLE
task submission "Write an android app that adds two numbers"

### ISSUE THREAD

**Issue by ViciousCupcake** [jboss-outreach/anonymous#93]
Screenshots-
![jb1](https://user-images.githubusercontent.com/22625405/33693074-47798f62-dab6-11e7-9052-807867357aa1.JPG)
![jb2](https://user-images.githubusercontent.com/22625405/33693075-4788bf64-dab6-11e7-924d-aefdaedcbe0f.JPG)
![jb3](https://user-images.githubusercontent.com/22625405/33693076-47981658-dab6-11e7-8d68-4b0cd64f3efa.JPG)
![jb4](https://user-images.githubusercontent.com/22625405/33693077-47a7e394-dab6-11e7-9b67-13c7e2c618df.JPG)
![jb5](https://user-images.githubusercontent.com/22625405/33693072-4750f804-dab6-11e7-88ed-7c13502dac88.JPG)
![jb6](https://user-images.githubusercontent.com/22625405/33693073-476a0466-dab6-11e7-9eb5-7f98c135da27.JPG)
apk (in zip because github doesnt supporting uploading apks)
[apk.zip](https://github.com/jboss-outreach/anonymous/files/1537396/apk.zip)
Thanks!

**Comment by opticod** [comment]
Good Work !
