### ISSUE TITLE
GCI : Install Android Studio 3.0

### ISSUE THREAD

**Issue by samuelmjn** [jboss-outreach/anonymous#97]
<img width="295" alt="screen shot 2017-12-09 at 02 37 19" src="https://user-images.githubusercontent.com/34322984/33782299-c57f4930-dc8a-11e7-8e93-ed65e76fd943.png">
<img width="853" alt="screen shot 2017-12-09 at 02 37 46" src="https://user-images.githubusercontent.com/34322984/33782306-c7b0b946-dc8a-11e7-900e-7822e440e34d.png">
<img width="848" alt="screen shot 2017-12-09 at 02 38 06" src="https://user-images.githubusercontent.com/34322984/33782308-c9eadc00-dc8a-11e7-900b-b0d96e6bbb14.png">
<img width="1301" alt="screen shot 2017-12-09 at 02 38 19" src="https://user-images.githubusercontent.com/34322984/33782313-ccbefa24-dc8a-11e7-8cde-7222b57d491c.png">

**Comment by yashovardhanagrawal** [comment]
LGTM
