### ISSUE TITLE
hello world app on Xcode for GCI

### ISSUE THREAD

**Issue by aiyaad** [jboss-outreach/anonymous#98]
![launcher icon](https://user-images.githubusercontent.com/34397118/33831430-1e3fbafe-de9e-11e7-9606-0d61414f7e30.png)
![hello world main page](https://user-images.githubusercontent.com/34397118/33831456-27a8150a-de9e-11e7-97aa-99b249a7a3cf.png)
![input name](https://user-images.githubusercontent.com/34397118/33831460-2f0f4ad4-de9e-11e7-90bb-39d5a4ea6e4a.png)
![hello world](https://user-images.githubusercontent.com/34397118/33831468-3343aae6-de9e-11e7-9488-5ffc80ba4955.png)
![screenshot of code](https://user-images.githubusercontent.com/34397118/33831569-949e8ba8-de9e-11e7-9e60-4226f65b2346.png)

**Comment by yashovardhanagrawal** [comment]
LGTM
